// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhQLzfS6EPbODKEZjsqvEl_SKd5TWjUE',
    appId: '1:331725744570:web:c03c599bd2bd268f5f1583',
    messagingSenderId: '331725744570',
    projectId: 'health-tracker-fa',
    authDomain: 'health-tracker-fa.firebaseapp.com',
    storageBucket: 'health-tracker-fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2PZZX9jCJToSIDTftY-BNKpRdUvdBzY',
    appId: '1:331725744570:android:93eeabe34bb409075f1583',
    messagingSenderId: '331725744570',
    projectId: 'health-tracker-fa',
    storageBucket: 'health-tracker-fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6ApzmBWRmywjw23QPMBV35sjtZ29WX4',
    appId: '1:331725744570:ios:f92bd7cd87702ac95f1583',
    messagingSenderId: '331725744570',
    projectId: 'health-tracker-fa',
    storageBucket: 'health-tracker-fa.firebasestorage.app',
    iosClientId: '331725744570-a70ffsfet2ms2tk10hkide55bjubbb3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6ApzmBWRmywjw23QPMBV35sjtZ29WX4',
    appId: '1:331725744570:ios:f92bd7cd87702ac95f1583',
    messagingSenderId: '331725744570',
    projectId: 'health-tracker-fa',
    storageBucket: 'health-tracker-fa.firebasestorage.app',
    iosClientId: '331725744570-a70ffsfet2ms2tk10hkide55bjubbb3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZhQLzfS6EPbODKEZjsqvEl_SKd5TWjUE',
    appId: '1:331725744570:web:875b3c6d03d556145f1583',
    messagingSenderId: '331725744570',
    projectId: 'health-tracker-fa',
    authDomain: 'health-tracker-fa.firebaseapp.com',
    storageBucket: 'health-tracker-fa.firebasestorage.app',
  );
}
